server:
  port: 5000
  servlet:
    context-path: /e-learning-portal

# spring
spring:
  application:
    name: '@project.artifactId@'
  datasource:
    url: jdbc:mysql://elearning-identifier-database.cojipqlkwari.us-east-2.rds.amazonaws.com:3306/elearningdatabase?serverTimezone=UTC
    username: root
    password: back22#password
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true
  jackson:
    serialization:
      INDENT_OUTPUT: true
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

jwt:
  token:
    secret: elearningportal
    expired: 3600000