server:
  port: 5000
  servlet:
    context-path: /e-learning-portal

# spring
spring:
  application:
    name: '@project.artifactId@'
  datasource:
    url: jdbc:mysql://e-learning-database-instance.cojipqlkwari.us-east-2.rds.amazonaws.com:3306/e_learning?serverTimezone=UTC
    username: root
    password: back22#password
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true
#  jackson:
#    serialization:
#      INDENT_OUTPUT: true

