server:
  port: 8080
  servlet:
    context-path: /e-learning-portal

# spring
spring:
  application:
    name: '@project.artifactId@'
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://10.58.112.4:3306/e_learning_database?serverTimezone=UTC
    username: root
    password: root
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true
#  jackson:
#    serialization:
#      INDENT_OUTPUT: true

