server:
  port: 8080
  servlet:
    context-path: /e-learning-portal

# spring
spring:
  application:
    name: '@project.artifactId@'
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://e_learning_database/?cloudSqlInstance=e-learning-back-end:europe-west2:e-learning-instance&socketFactory=com.google.cloud.sql.mysql.SocketFactory

    url: jdbc:mysql://10.58.112.4/e_learning_database?serverTimezone=UTC
    username: root
    password: root
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true
#  jackson:
#    serialization:
#      INDENT_OUTPUT: true

